---
sudo: false
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'

cache: pip

install:
  - travis_retry pip install --upgrade --requirement requirements-dev.txt
  - pip install .

script:
  - flake8
  - python -Wall -m unittest discover tests

notifications:
  email: false

deploy:
  provider: pypi
  user: managedbyq
  password:
    secure: La8ziI+d8zjMTDMBSKGTQVLWPWdpxGN3+bBuJAUGq5BTermo1Oe2qtNzMMIDtEzuBDobR8pTmiHeAtiGh4PRXzAkQdO6GqhXCcGZmO0s555mnsD13ZUqbQLz4SJNViqiNDDY8lP+tiXm57J1gnbsRzyt/uwygrCFBKXEh4p69KrVK8AwH8CMcFfbjE4Szt+EllqB83loe9yoS6S0Ty/0PEyWzqSxIG15HuCbff5/yH8pLicZM9mj60bEGGTu1LtGTZXAve12MSh3u1sBCg3uQCNstSiSbNNTARnhEaGcuD4ZvDqkYNMG3TX4CN6aox2M9Y6WVnRGT4sTpo83soB4GdKKUqO0p3NgFu0j1BkgzBgcJhQkQAAjSUyAnNMxoI6UjcLWRHf4QBgrT06Hd+8rPC6Kp0HtIkwMqzEiNB8OPsUVjc9K7ZgktIl1UMJPBUvsRSjSkVut0JIB7ml5bFYnsjfA2P1WUfoN3D/ziydBma0rgfEPRt/qgcQyNpnxBTL2NKq/VaJKJAxMWQu1xRitqicy1oMsuuPmKM594Qn9oseP3q0A2Tv29kQTueWl8QDIoMimCeetXh9uUrR/VdZMZUZip0yAEllV343XIjfwevUG1nD8xfpL011E0YteV/QECQhOc6STgVUHq1/Xj92WPthdJfjY9/QOG6wTx81KJd0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    python: '3.6'
    repo: managedbyq/mbq.env
